export interface ICuenta {
  token: string,
  type: string,
  status: string,
  createdOn: Date,
  transferMethodCountry: string,
  transferMethodCurrency: string,
  branchId: string,
  bankAccountId: string,
  bankAccountRelationship: string,
  bankAccountPurpose: string,
  profileType: string,
  firstName: string,
  lastName: string,
  dateOfBirth: Date,
  addressLine1: string,
  city: string,
  stateProvince: string,
  country: string,
  postalCode: number,
}